### ISSUE TITLE
gzipSize looks too small

### ISSUE THREAD

**Issue by makryl** [hansifer/grunt-file-info#4]
Hi.
Looks like `require('zlib-browserify').gzipSync` expects Buffer instead of string.
I'm not sure, but if wrap file contents in `Buffer` function, gzipped file size looks better (compared with console `gzip` command):
```
function gzipSize(filepath) {
    return require('zlib-browserify').gzipSync(Buffer(grunt.file.read(filepath))).length;
  }
```
May be this is bug in zlib-browserify.

**Comment by hansifer** [comment]
Code updated. Thanks for the heads up!

**Comment by KrylosovM** [comment]
Thank you :)
